1st
組み合わせを全探索して一致するものがあれば出力する。
問題の制約上、ターゲットと一致する合計の組み合わせは存在するが、
存在しない場合は例外を発生させる。
プログラムの一貫性が重要で、期待する出力が必ずあるべきケースや、異常事態で処理を止めたい場合などは例外発生させる。

時間計算量：O(n^2)
空間計算量：O(1)

```python
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for i in range(len(nums)):
            for j in range(i + 1, len(nums)):
                two_sum = nums[i] + nums[j]
                if target == two_sum:
                    return [i, j]
        raise Exception("No Solution Found")
```

2nd
1st を読みやすくする。
思いつかなかったので、例外を発生させるのではなく、空配列を返すようにした。
ここは要件によると思う。
空の結果が正常なケースとして扱われる場合や、エラーを起こさず処理を続けたい場合は空の配列を返す選択をする。
https://github.com/seal-azarashi/leetcode/pull/11#discussion_r1672537855

```python
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for i in range(len(nums)):
            for j in range(i + 1, len(nums)):
                current_sum = nums[i] + nums[j]
                if target == current_sum:
                    return [i, j]
        return []
```

辞書を使った解法

野田さんのコメントを見て、num_to_indexes にした。
https://github.com/takumihara/leetcode/pull/1#discussion_r1805676834
Exception よりもより具体的な ValueError を使った。
https://github.com/takumihara/leetcode/pull/1#discussion_r1806764103

時間計算量：O(n)
空間計算量：O(n)

```python
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        num_to_indexes = {}
        for index, num in enumerate(nums):
            difference = target - num
            if difference in num_to_indexes:
                return [num_to_indexes[difference], index]
            num_to_indexes[num] = index
        raise ValueError("Ensure that there exists a unique pair in 'nums' that sums up to the 'target' value")
```

3rd

```python
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        num_to_indexes = {}
        for index, num in enumerate(nums):
            difference = target - num
            if difference in num_to_indexes:
                return [num_to_indexes[difference], index]
            num_to_indexes[num] = index
        raise ValueError("Ensure that there exists a unique pair in 'nums' that sums up to the 'target' value")
```
